theme: jekyll-theme-minimal
title: Dhyan Aranha 
description: Post-doc University of Amsterdam

url: "http://dhyan-aranha.github.io" # the base hostname & protocol for your site
plugins:
  - jekyll-sitemap

